routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('operation.commission.create');
});

Route::group(['namespace' => 'Operation', 'prefix' => 'operation', 'as' => 'operation.'], function () {
    /*
     * These routes need for operation permission
     */
    /*TODO::*/
    Route::get('commissions/generate',[\App\Http\Controllers\Operation\FileUploadController::class,'create'])->name('commission.create');
    Route::get('commissions',[\App\Http\Controllers\Operation\FileUploadController::class,'index'])->name('commission.index');
    Route::post('commissions/generate',[\App\Http\Controllers\Operation\FileUploadController::class,'store'])->name('commission.store');
});

app/Http/Controllers/Operation/FileUploadController.php
<?php

namespace App\Http\Controllers\Operation;

use App\Http\Controllers\Controller;
use App\Http\Requests\CommissionRequest;
use App\Services\CommissionCalculationService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class FileUploadController extends Controller
{
    /**
     * @param Request $request
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $commissionData = Cache::get('commissionData');
        if ($commissionData) {
            $items = json_decode($commissionData, true);
        } else {
            $items = [];
        }
        $data['items'] = $items;
        $weekly_commission_free = Cache::get('weekly_commission_free');
        $currencies = Cache::get('currencies');
        $data['weekly_commission_free'] = ($weekly_commission_free) ? json_decode($weekly_commission_free, true) : [];
        $data['currencies'] = ($currencies) ? json_decode($currencies,true) : [];
        $data['i'] = 1;
        return view('operation.commission.index', $data);
    }

    /**
     * @param Request $request
     * @return Application|Factory|View|void
     */
    public function create(Request $request)
    {
        try {
            return view('operation.commission.create');
        } catch (\Exception $exception) {
            \Log::error("File Upload Error: " . $exception->getMessage());
        }
    }


    /**
     * @param CommissionRequest $request
     * @return RedirectResponse
     */
    public function store(CommissionRequest $request): \Illuminate\Http\RedirectResponse
    {
        try {
            $uploadFIle = $request->file('commission_file');
            $fileType = $uploadFIle->getClientMimeType();
            if ($fileType == 'text/csv') {
                $results = csv_to_array($uploadFIle->getRealPath(), ',');
            } else {
                throw new \Exception("Invalid file format   : " . $fileType . " .Valid file format is text/csv. ");
            }
            Cache::forget('commissionData');
            Cache::forget('weekly_commission_free');
            $commissionData = array();

            if (count($results)) {
                $commissionService = new CommissionCalculationService();
                foreach ($results as $result) {
                    if( !isset($result['user_type']) || !isset($result['operation_type']) || !isset($result['operation_amount']) || !isset($result['operation_date']) || !isset($result['currency'])) {
                        throw new \Exception("Missing required data.");
                    }
                    $commissionAmt = $commissionService->calculateCommission($result['user_type'], $result['operation_type'], $result['operation_amount'], $result['currency'], $result['operation_date']);
                    $result['commission'] = $commissionAmt;
                    $commissionData[] = $result;
                }
            }

            $seconds = config('misc.cache.currencies');
            Cache::add('commissionData', json_encode($commissionData), $seconds);
            return redirect()->route('operation.commission.index')->with('success', 'Commission is calculated properly.');
        } catch (\Exception $exception) {
            $message = ($exception->getMessage()) ? $exception->getMessage() : "Something went wrong";
            return redirect()->back()->with('error', $message);
        }
    }
}

resources/views/operation/commission/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">{{ __('Commission File Upload') }}</div>

        <div class="card-body">
            <form method="POST" action="{!! route('operation.commission.store') !!}" enctype="multipart/form-data">
                @csrf

                <div class="row mb-3">
                    <label for="file_name" class="col-md-4 col-form-label text-md-end">{{ __('File Name') }}</label>

                    <div class="col-md-6">
                        <input id="file_name" type="text" class="form-control @error('file_name') is-invalid @enderror" name="file_name" value="{{ old('file_name') }}" required autocomplete="file_name" autofocus>

                        @error('file_name')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="email" class="col-md-4 col-form-label text-md-end">{{ __('Uploader Email Address') }}</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                        @error('email')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="commission_file" class="col-md-4 col-form-label text-md-end">{{ __('Upload Commission File') }}</label>

                    <div class="col-md-6">
                        <input id="commission_file" type="file" class="form-control @error('commission_file') is-invalid @enderror" name="commission_file"  required  >

                        @error('commission_file')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                        <ul class="small">
                            <li>
                                             <span>
                                               Demo file upload format. To download <a href="{!! asset('demo/demo_commission_upload_file_1.csv') !!}" autofocus> Click Here</a>
                                             </span>
                            </li>
                            <li>File type will be text/csv </li>
                            <li>File format must be as like demo file </li>
                            <li>Operation date in format Y-m-d </li>
                            <li>User's identifier, number</li>
                            <li>User's type, one of private or business</li>
                            <li>Operation type, one of deposit or withdraw</li>
                            <li>Operation amount (for example 2.12 or 3)</li>
                            <li>Operation currency, one of EUR, USD, JPY</li>
                        </ul>
                    </div>
                </div>
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Upload') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/operation/commission/index.blade.php
@extends('layouts.app')

@section('content')

    <p>
        To upload another commission file please click here.
        <a href="{!! route('operation.commission.create') !!}"> Click Me</a>
    </p>

        <div class="col-md-12">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Operation Date</th>
                    <th scope="col">Number</th>
                    <th scope="col">User Type</th>
                    <th scope="col">Operation Type</th>
                    <th scope="col">Operation Amount</th>
                    <th scope="col">Currency</th>
                    <th scope="col">Commission</th>
                </tr>
                </thead>
                <tbody>
                @if(count($items))
                    @foreach($items as $key=>$item)
                        <tr>
                            <th scope="row">{!! $key+1 !!}</th>
                            <td>{!! $item['operation_date'] ?? '' !!}</td>
                            <td>{!! $item['number'] ?? '' !!}</td>
                            <td>{!! $item['user_type'] ?? '' !!}</td>
                            <td>{!! $item['operation_type'] ?? '' !!}</td>
                            <td>{!! $item['operation_amount'] ?? '' !!}</td>
                            <td>{!! $item['currency'] ?? '' !!}</td>
                            <td>{!! $item['commission'] ?? '' !!}</td>
                        </tr>
                    @endforeach
                @endif

                </tbody>
            </table>
        </div>
    <br>
    <div class="col-md-12">
        <h4>Weekly Commission Free </h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">WeekNo</th>
                <th scope="col">StartDate</th>
                <th scope="col">EndDate</th>
                <th scope="col">Commission Amount</th>
                <th scope="col">Commission Count</th>
                <th scope="col">Currency</th>

            </tr>
            </thead>
            <tbody>
            @if(count($weekly_commission_free))
                @foreach($weekly_commission_free as $key=>$commissionFree)
                    <tr>
                        <th scope="row">{!! $key+1 !!}</th>
                        <td>{!! $commissionFree['week_no'] ?? '' !!}</td>
                        <td>{!! $commissionFree['start_date'] .''. \Carbon\Carbon::parse($commissionFree['start_date'])->dayName !!}</td>
                        <td>{!! $commissionFree['end_date'] .''. \Carbon\Carbon::parse($commissionFree['end_date'])->dayName !!}</td>
                        <td>{!! $commissionFree['free_total_amount'] ?? '' !!}</td>
                        <td>{!! $commissionFree['free_total_count'] ?? '' !!}</td>
                        <td>{!!  'EUR' !!}</td>
                    </tr>
                @endforeach
            @endif

            </tbody>
        </table>
    </div>
    <br>
    <div class="col-md-12">
        <h4>Currency Exchange Rate</h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Currency Name</th>
                <th scope="col">Rates</th>
                <th scope="col">Base</th>

            </tr>
            </thead>
            <tbody>
            @if(count($currencies))
                @foreach($currencies as $key=>$currency)
                    <tr>
                        <td>{!! $i++; !!}</td>
                        <td>{!! $key ?? '' !!}</td>
                        <td>{!! $currency ?? '' !!}</td>
                        <td>{!!  'EUR' !!}</td>

                    </tr>
                @endforeach
            @endif

            </tbody>
        </table>
    </div>


@endsection